---
- name: Build, Push and Run docker with Python app.
  hosts: localhost
  gather_facts: yes
  become: no

  vars:
    ansible_python_interpreter: "/opt/homebrew/bin/python3"
    image_name: "tonci123/devops-programme"
    image_tag: "latest"
    listen_port: "8080"
    image_repo: "tonci123/devops-programme"
    dockerfile_path: "../"

  tasks:
    - name: Build docker image
      docker_image:
        docker_host: "unix://{{ ansible_env.HOME }}/.docker/run/docker.sock"
        name: "{{ image_name }}"
        tag: "{{ image_tag }}"
        build:
          path: "{{ dockerfile_path }}"
          pull: yes
#        repository: "{{ image_repo }}"
        source: build
#        push: yes
        state: present
